// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  "use strict";
  var Webhook, assert, crypto, domain, exec, express, extend, fs, iced, path, __iced_k, __iced_k_noop,
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  express = require("express");

  crypto = require("crypto");

  assert = require("assert");

  domain = require("domain");

  fs = require("fs");

  path = require("path");

  exec = require("child_process").exec;

  extend = function() {
    var key, source, sources, target, val, _i, _len;
    target = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = sources.length; _i < _len; _i++) {
      source = sources[_i];
      for (key in source) {
        val = source[key];
        target[key] = val;
      }
    }
    return target;
  };

  Webhook = (function() {
    Webhook.prototype.defaults = {
      ALGORITHM: "cast5-cbc",
      FORMAT: "base64",
      namespace: "",
      port: process.env.PORT || 10010,
      script: "./webhook",
      secret: process.env.WH_SECRET || "keyboard cat",
      type: "shell",
      basedir: process.cwd()
    };

    function Webhook(options) {
      var key;
      if (options == null) {
        options = {};
      }
      this.executeNodeModule = __bind(this.executeNodeModule, this);
      this.executeShellScript = __bind(this.executeShellScript, this);
      this.listenForWebhook = __bind(this.listenForWebhook, this);
      options = extend({}, this.defaults, options);
      for (key in this.defaults) {
        this[key] = options[key];
      }
      this.app || (this.app = express());
    }

    Webhook.prototype.start = function() {
      this.app.use(express.bodyParser());
      this.app.use(express.errorHandler());
      this.app.use(express.logger());
      this.app.post(path.join("/", this.namespace, ":hash"), this.listenForWebhook);
      return this.app.listen(this.port);
    };

    Webhook.prototype.listenForWebhook = function(req, res, next) {
      var dir, err, executeHook, exists, fullpath, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      if (!req.params.hash) {
        console.warn("missing hash", req.params.hash);
        return res.send(404);
      }
      try {
        dir = this.decrypt(req.params.hash, this.secret);
      } catch (_error) {
        err = _error;
        if (err.toString().match(/DecipherFinal/)) {
          console.warn("could not decipher", req.params.hash);
          return res.send(404);
        } else {
          return next(err);
        }
      }
      fullpath = path.join(this.basedir, dir);
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/index.iced",
          funcname: "Webhook.listenForWebhook"
        });
        fs.exists(fullpath, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return exists = arguments[0];
            };
          })(),
          lineno: 54
        }));
        __iced_deferrals._fulfill();
      })(function() {
        if (!exists) {
          console.warn("directory does not exist!", fullpath);
          return res.send(404);
        }
        console.info(dir);
        executeHook = (function() {
          switch (this.type) {
            case "node":
              return this.executeNodeModule;
            default:
              return this.executeShellScript;
          }
        }).call(_this);
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "src/index.iced",
            funcname: "Webhook.listenForWebhook"
          });
          executeHook(fullpath, req.body, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 65
          }));
          __iced_deferrals._fulfill();
        })(function() {
          if (err) {
            return next(err);
          }
          return res.send(200);
        });
      });
    };

    Webhook.prototype.sane = function(value) {
      return /^[a-zA-Z0-9 _\-+=,.;:'"?!@#%\^&*()<>\[\]{}|\\/\t]+$/.test(value);
    };

    Webhook.prototype.executeShellScript = function(dir, params, autocb) {
      var cmdWithArgs, err, key, textParams, value, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = autocb;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      textParams = (function() {
        var _results;
        _results = [];
        for (key in params) {
          value = params[key];
          if (this.sane(value)) {
            _results.push("" + key + "=\"" + value + "\"");
          }
        }
        return _results;
      }).call(this);
      cmdWithArgs = this.script + " " + textParams.join(" ");
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/index.iced",
          funcname: "Webhook.executeShellScript"
        });
        exec(cmdWithArgs, {
          cwd: dir
        }, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return err = arguments[0];
            };
          })(),
          lineno: 75
        }));
        __iced_deferrals._fulfill();
      })(function() {
        autocb(err);
        return;
      });
    };

    Webhook.prototype.executeNodeModule = function(dir, params, autocb) {
      var err, mod, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = autocb;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      mod = require(path.join(dir, this.script));
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/index.iced",
          funcname: "Webhook.executeNodeModule"
        });
        mod.hook(params, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return err = arguments[0];
            };
          })(),
          lineno: 80
        }));
        __iced_deferrals._fulfill();
      })(function() {
        autocb(err);
        return;
      });
    };

    Webhook.prototype.getId = function() {
      return os.hostname() + this.cwd;
    };

    Webhook.prototype.encrypt = function(id, password) {
      var final, projectCipher;
      assert.ok(id);
      assert.ok(password);
      projectCipher = crypto.createCipher(this.ALGORITHM, password);
      final = projectCipher.update(id, "utf8", this.FORMAT);
      final += projectCipher.final(this.FORMAT);
      return final;
    };

    Webhook.prototype.decrypt = function(encrypted, password) {
      var final, projectDecipher;
      assert.ok(encrypted);
      assert.ok(password);
      projectDecipher = crypto.createDecipher(this.ALGORITHM, password);
      final = projectDecipher.update(encrypted, this.FORMAT, "utf8");
      final += projectDecipher.final("utf8");
      return final;
    };

    Webhook.prototype.hashDir = function(dir, secret) {
      if (dir == null) {
        dir = "./";
      }
      if (secret == null) {
        secret = this.secret;
      }
      return encodeURIComponent(this.encrypt(dir, secret));
    };

    return Webhook;

  })();

  module.exports = Webhook;

}).call(this);
